#!/usr/bin/env python3
"""Generate JSONL files from large-model vision predictions."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from generate_jsonl import generate_jsonl, get_output_files


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert vision_predictions_large_model.csv into large-model JSONL files.",
    )
    parser.add_argument(
        "--csv",
        default=Path("vision_predictions_large_model.csv"),
        type=Path,
        help="Input CSV generated by component_classifier_large.onnx.",
    )
    parser.add_argument(
        "--knowledge",
        default=Path("knowledge/component_knowledge.json"),
        type=Path,
        help="Component knowledge JSON path.",
    )
    parser.add_argument(
        "--threshold",
        default=Path("configs/threshold.json"),
        type=Path,
        help="Confidence threshold config JSON path.",
    )
    parser.add_argument(
        "--out-dir",
        default=Path("."),
        type=Path,
        help="Output directory for electronics_*_large_model.jsonl files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_suffix = "_large_model"

    try:
        counts = generate_jsonl(
            csv_path=args.csv,
            knowledge_path=args.knowledge,
            threshold_path=args.threshold,
            out_dir=args.out_dir,
            output_suffix=output_suffix,
        )
    except Exception as exc:
        print(f"Error: {exc}")
        return 1

    print("Large-model JSONL generation complete.")
    output_files = get_output_files(output_suffix)
    for split in ("train", "validation", "test"):
        print(f"{output_files[split]}: {counts[split]} records")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
